version: "3.8"
services:
  app:
    container_name: php
    build:
      context: ./infrastructure/php
      dockerfile: ./Dockerfile
    volumes:
      - ./application:/var/www
    tty: true

  web:
    container_name: nginx
    image: nginx:1.21.4-alpine
    ports:
      - 8080:80
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www
    working_dir: /var/www

  db:
    container_name: mysql
    build: ./infrastructure/mysql
    ports:
      - 3307:3306
    volumes:
      - db-store:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  db-store:
  redis: